import io
from app.models.research import Report

def generate_report_pdf(report: Report) -> bytes:
    from reportlab.lib.pagesizes import letter
    from reportlab.pdfgen import canvas
    
    # minimal dummy implementation
    packet = io.BytesIO()
    c = canvas.Canvas(packet, pagesize=letter)
    c.drawString(100, 750, "DeepResearch AI Report")
    c.drawString(100, 730, f"Title: {report.title}")
    c.drawString(100, 710, f"Generated: {report.created_at}")
    c.drawString(100, 50, "Generated by DeepResearch AI - Page 1")
    c.showPage()
    c.save()
    packet.seek(0)
    return packet.read()
