"""align_user_model

Revision ID: a645e8bffa13
Revises: 2e5c0266086c
Create Date: 2026-03-11 00:08:56.777958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a645e8bffa13'
down_revision: Union[str, None] = '2e5c0266086c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_constraint(op.f('users_clerk_id_key'), 'users', type_='unique')
    op.drop_column('users', 'clerk_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clerk_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_clerk_id_key'), 'users', ['clerk_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
